### ISSUE TITLE
AMS Courses

### ISSUE THREAD

**Issue by lisajscott82** [philbarker/macsstudent_wptheme#18]
Requirements for AMS Course Types

Basic Course Data should be taken from C4 Forms and displayed.

Additionaly requirements:
Reading (to be added)
Detailed Syllabus (already added)
Summary (may possibly be required in future)?

**Comment by philbarker** [comment]
Use the same extended course metadata box for Maths and AMS (they can ignore what they don't need)

- [ ] Add reading list custom field to admin interface (wysiwyg type)
- [ ] Display info about reading list
- [ ] Add summary field to admin interface (wysiwyg type)
- [ ] Display info from summary field
