### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by lisajscott82** [philbarker/macsstudent_wptheme#6]
Notice: Undefined index: type in /var/www/html/macs/students/wp-content/themes/macsstudent_wptheme/macs-taxonomies.php on line 101 

Appearing on http://www.macs.hw.ac.uk/students/cs/courses1/

**Comment by philbarker** [comment]
It was an error in the short code I used when testing posts-by-taxon
[posts-by-taxon level=7 orderby="title" order="desc" type="cs-course] <--must close quotes at end!

Fixed now, so closing but posts_by_taxon clearly needs more error testing. related: #5
