### ISSUE TITLE
Linked Courses

### ISSUE THREAD

**Issue by lisajscott82** [philbarker/macsstudent_wptheme#7]
List of possible linked courses doen't appear when adding CS Courses. I need to link F20PA, F20PB and F20PC as synoptic courses. Only option I get is one sample maths course code (F17CC).

**Comment by philbarker** [comment]
Have made hot-fix on installed files which I think should work but cannot test from here.

to-do: make fix to repository files.

**Comment by lisajscott82** [comment]
Installed version works now. Thanks.
